version: '3'
services:
    php:
        container_name: ajandera_server
        build: arualcms/api/docker
        volumes:
            - ./arualcms/api:/var/www/html:delegated
        ports:
            - 8888:80
        environment:
            HTTPD__DocumentRoot: '/var/www/html/'
            HTTPD__ServerAdmin: 'ales.jandera@gmail.com'
            HTTPD_a2enmod:  'rewrite status expires'
    mongo:
        container_name: ajandera_mongo
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 3FSFSDFDFrew
            MONGO_INITDB_DATABASE: arualcms
        ports:
            - "27017:27017"
        volumes:
            - ./arualcms/data:/data/db
            #- ./arualcms/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
