version: '3'
services:
    php:
        container_name: ajandera_server
        build: arualcms/api/docker
        volumes:
            - ./arualcms:/var/www/html:delegated
        ports:
            - 8000:80
        environment:
            HTTPD__DocumentRoot: '/var/www/html/'
            HTTPD__ServerAdmin: 'ales.jandera@gmail.com'
            HTTPD_a2enmod:  'rewrite status expires'
    vue-front:
        build: ./site
        ports:
            - "9000:9000"
        container_name: ajandera_front
        volumes:
            - ./site:/usr/src/app
            - /usr/src/app/node_modules
