version: '3'
services:
    php:
        container_name: ajandera_server
        image: ajandera/arualcms
        ports:
            - 8000:80
        volumes:
            - ./arualcms/storage:/var/www/html/api/www/storage:delegated
        environment:
            mongo_dsn: 'mongodb://root:3FSFSDFDFrew@mongo:27017'
    mongo:
        container_name: ajandera_mongo
        image: mongo
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: 3FSFSDFDFrew
            MONGO_INITDB_DATABASE: arualcms
        ports:
            - "27017:27017"
        volumes:
            - ./arualcms/data:/data/db
            #- ./arualcms/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d:ro
