version: 2

jobs:
  deploy:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: installation
          command: |
             sudo apt-get update; sudo apt-get install openssh ssh-pass
      - run:
          name: Install packages
          command: cd site && npm install
      - run:
          name: Build and minify app
          command: cd site && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - run:
         name: Deploy Over SSH
         command: | 
            sshpass -p '$SSH_PASS' scp -P 5051 -r ~/dist "$SSH_USER@$SSH_HOST:$SSH_DEPLOY_PATH"
workflows:
  version: 2
  main:
    jobs:
      - deploy
