version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    working_directory: ~/site
    steps:
      - checkout
      - run:
          name: Install packages
          command: npm ci
      - run:
          name: Build and minify app
          command: npm run build
      - run:
          name: Deploy to cloud server
          command: npm run deploy
workflows:
  version: 2
  main:
    jobs:
      - deploy
