version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.15.3-stretch
    steps:
      - checkout
      - run:
          name: Install packages
          command: yarn install
      - run:
          name: Build and minify app
          command: yarn build
      - run:
          name: Deploy to cloud server
          command: yarn deploy
workflows:
  version: 2
  main:
    jobs:
      - deploy
