version: 2

jobs:
  deploy:
    docker:
      - image: circleci/node:10.8.0
    steps:
      - checkout
      - run:
          name: Install packages
          command: cd site && npm install
      - run:
          name: Build and minify app
          command: cd site && npm run build
      - persist_to_workspace:
          root: .
          paths:
            - '*'
      - run:
          name: Deploy to cloud server
          command: cd site && npm run deploy
workflows:
  version: 2
  main:
    jobs:
      - deploy
